name: Scrape church events
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install deps
        run: yarn
        
      - name: Run scraper
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: yarn scrape
